### ISSUE TITLE
Obsolete doc for Jennifer

### ISSUE THREAD

**Issue by Pepan** [amberframework/docs#133]
Hi.
I am new to Crystal and Amber - coming from Rails world ... so I don't know how to fix that... but following doc for Jennifer leads to not working environment
```
 crystal sam.cr -- generate:migration CreateUser
Error: unknown command: sam.cr
```
I manage to run sam.cr by moving it from src/ to ./ and fixing paths
- but it leads to errors like 
```
Error in src/sam.cr:3: undefined local variable or method '​'
```
fixed by jumping to next line and press del until it jumps to above line - then enter to move it to new line ... there are some strange characters in code taken from doc ...

- i am very lazy from Ruby and Rails and this not working guerrilla environment makes me frustrated ...
Jennifer is open gate for people like me and we will not try some experimental ORM which are default and are not able to manage things way I am accustomed from ActiveRecord ... I thing that default should be Jennifer for smooth transition ;) to try Crystal and Amber. And if somebody is not satisfied with AR - they he can try some new ...

**Comment by drujensen** [comment]
> Jennifer is open gate for people like me and we will not try some experimental ORM which are default and are not able to manage things way I am accustomed from ActiveRecord

Jennifer is just as experimental as Granite.  I find Granite is actually closer to ActiveRecord in many ways i.e. finders and relationships.  Did you try both to make this judgement call?

**Comment by drujensen** [comment]
Yeah, this is a nice DSL:
```
class CreateContact < Jennifer::Migration::Base
  def up
    # Postgres requires to create specific enum type
    create_enum(:gender_enum, ["male", "female"])
    create_table(:contacts) do |t|
      t.string :name, {:size => 30}
      t.integer :age
      t.integer :tags, {:array => true}
      t.field :gender, :gender_enum
      t.timestamps
    end
  end

  def down
    drop_table :contacts
    drop_enum(:gender_enum)
  end
end
```

**Comment by eliasjpr** [comment]
Addressed with https://github.com/amberframework/docs/pull/186
