### ISSUE TITLE
Old stats in frontpage

### ISSUE THREAD

**Issue by ChangJoo-Park** [amberframework/docs#76]
![image](https://user-images.githubusercontent.com/1451365/38726936-90fda214-3f46-11e8-990e-e8ba562c4271.png)

version, github stars and commits are too old.
Where can I change these?

**Comment by faustinoaq** [comment]
right here :point_down: 

https://github.com/amberframework/amberframework.org/blob/425890653c08e2cb21542322101bb047c7c765fc/src/views/home/index.slang#L114-L131

We used to use an script, but was a bit buggy, so we removed it :sweat_smile:

**Comment by faustinoaq** [comment]
Stats has been updated :tada:
